//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalEventsSeminarski_API.Models
{
    using System;
    
    public partial class esp_Event_Top5ByGradMjesec_Result1
    {
        public int EventID { get; set; }
        public string Naziv { get; set; }
        public string DatumOdrzavanja { get; set; }
        public string Lokacija { get; set; }
        public string Grad { get; set; }
        public double AverageRating { get; set; }
    }
}
