//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalEventsSeminarski_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventGalleries = new HashSet<EventGallery>();
            this.EventToVisits = new HashSet<EventToVisit>();
            this.AgeRanges = new HashSet<AgeRange>();
        }
    
        public int EventID { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public int KreatorID { get; set; }
        public double AverageRating { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public System.DateTime DatumOdrzavanja { get; set; }
        public Nullable<System.TimeSpan> VrijemePocetka { get; set; }
        public Nullable<System.TimeSpan> VrijemeZavrsetka { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
        public string Status { get; set; }
        public int EventTipID { get; set; }
        public Nullable<int> OrganizacijaID { get; set; }
        public int LokacijaID { get; set; }
    
        public virtual EventTip EventTip { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Lokacija Lokacija { get; set; }
        public virtual Organizacija Organizacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventGallery> EventGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventToVisit> EventToVisits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgeRange> AgeRanges { get; set; }
    }
}
