//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalEventsSeminarski_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosjetilacOrganizacija
    {
        public int PosjetilacID { get; set; }
        public int OrganizacijaID { get; set; }
        public Nullable<int> LocationRating { get; set; }
        public Nullable<System.DateTime> RatingDate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
    
        public virtual Organizacija Organizacija { get; set; }
        public virtual Posjetilac Posjetilac { get; set; }
    }
}
