//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalEventsSeminarski_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posjetilac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posjetilac()
        {
            this.EventToVisits = new HashSet<EventToVisit>();
            this.PosjetilacLokacijas = new HashSet<PosjetilacLokacija>();
            this.PosjetilacOrganizacijas = new HashSet<PosjetilacOrganizacija>();
        }
    
        public int PosjetilacID { get; set; }
        public Nullable<int> BrojPosjecenihDogadjaja { get; set; }
        public string Zanimanje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventToVisit> EventToVisits { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosjetilacLokacija> PosjetilacLokacijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosjetilacOrganizacija> PosjetilacOrganizacijas { get; set; }
    }
}
