//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalEventsSeminarski_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slika
    {
        public int SlikaID { get; set; }
        public int EventGalleryID { get; set; }
        public byte[] Slika1 { get; set; }
        public byte[] SlikaThumb { get; set; }
        public string Opis { get; set; }
    
        public virtual EventGallery EventGallery { get; set; }
    }
}
