//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalEventsSeminarski_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalEventsSeminarski_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select at least one age range!.
        /// </summary>
        internal static string ageRange_check_err {
            get {
                return ResourceManager.GetString("ageRange_check_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is taken!.
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Format!.
        /// </summary>
        internal static string field_format_err {
            get {
                return ResourceManager.GetString("field_format_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field!.
        /// </summary>
        internal static string field_req {
            get {
                return ResourceManager.GetString("field_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity can&apos;t be a negative value!.
        /// </summary>
        internal static string kapacitet_err {
            get {
                return ResourceManager.GetString("kapacitet_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is larger than maximum capacity value..
        /// </summary>
        internal static string kapacitet_err2 {
            get {
                return ResourceManager.GetString("kapacitet_err2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password!.
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Not Found or Account Not Active!.
        /// </summary>
        internal static string login_username_err {
            get {
                return ResourceManager.GetString("login_username_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be at least two characters long!.
        /// </summary>
        internal static string naziv_length_error {
            get {
                return ResourceManager.GetString("naziv_length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be at least 20 characters long!.
        /// </summary>
        internal static string opis_length_err {
            get {
                return ResourceManager.GetString("opis_length_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long!.
        /// </summary>
        internal static string password_register_error {
            get {
                return ResourceManager.GetString("password_register_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain letters and numbers!.
        /// </summary>
        internal static string password_register_error2 {
            get {
                return ResourceManager.GetString("password_register_error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo you choose is too small!.
        /// </summary>
        internal static string picture_war {
            get {
                return ResourceManager.GetString("picture_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a .jpg file!.
        /// </summary>
        internal static string slika_error {
            get {
                return ResourceManager.GetString("slika_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is taken!.
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 5 characters long!.
        /// </summary>
        internal static string username_register_error {
            get {
                return ResourceManager.GetString("username_register_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain letters and numbers!.
        /// </summary>
        internal static string username_register_error2 {
            get {
                return ResourceManager.GetString("username_register_error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
